////////////////////////////////////////////////////////////////////////////////
// $file             PREFERENCES_SCRIPTS.SSL
// $author           Scenomics LLC
// $privacy          PUBLIC
// $description      This script implements basic preferences set/get.
// $legal            Reserved * r_rLegal
//
// Copyright 2004-2014 Scenomics LLC. All Rights Reserved.
////////////////////////////////////////////////////////////////////////////////

// DEPRECATED MJR 07-26-2014