#ifndef SPA_VIEW
#define SPA_VIEW 
#include <SPA_Constants.glsl>

/////////////////////////////////////////////////////////////////////////////////
// View Data Structures
/////////////////////////////////////////////////////////////////////////////////

/* This file is automatically generated and will be overwritten. To change this
file, start the Shader application and open INCLUDES\SPA_VIEW.BOX. */

/* ABOUT: This is the view struct and uniform block. These are included in shader
source code remotely, and should not be duplicated per-shader. Different types
of view variables should be defined here. */
struct SPA_View
{
   float viewportWidth;
   float viewportHeight;
   vec4 viewportViewPosition;
   vec4 viewportViewOrientation;
   mat4x4 modelMatrix;
   mat4x4 modelViewMatrix;
   mat4x4 modelViewProjectionMatrix;
   mat4x4 textureMatrix;
   mat3x3 normalMatrix;
   mat4x4 viewMatrix;
};

uniform SPA_ViewBlock
{
   SPA_View view;
};


// !SPA_VIEW

#endif
