#ifndef SPA_MATERIALS
#define SPA_MATERIALS 
#include <SPA_Constants.glsl>

/////////////////////////////////////////////////////////////////////////////////
// Material Data Structures
/////////////////////////////////////////////////////////////////////////////////

/* This file is automatically generated and will be overwritten. To change this
file, start the Shader application and open INCLUDES\SPA_MATERIALS.BOX. */

/* ABOUT: This is the material struct and uniform block. These are included in
shader source code remotely, and should not be duplicated per-shader. Different
types of materials should be defined here. */
int infoCount = int( 4 );
uint arrayMax = uint( 1 );
struct SPA_Material
{
   vec4 materialAmbientColor;
   vec4 materialDiffuseColor;
   vec4 materialSpecularColor;
   vec4 materialEmissiveColor;
   int materialSolid;
   float materialShininess;
};

uniform SPA_MaterialsBlock
{
   SPA_Material materials;
   vec4 pink;
};


// !SPA_MATERIALS

#endif
