#ifndef SPA_GUIDES
#define SPA_GUIDES 
#include <SPA_Constants.glsl>

/////////////////////////////////////////////////////////////////////////////////
// Guides Data Structures
/////////////////////////////////////////////////////////////////////////////////

// This file is automatically generated and will be overwritten. To change this
// file, start the Shader application and open INCLUDES\SPA_GUIDES.BOX. */

// ABOUT: This is the guide struct and uniform block. These are included in shader
// source code remotely, and should not be duplicated per-shader. Different types
// of guide variables should be defined here.

struct SPA_Guides
{
   bool G_Vertices;
};

uniform SPA_GuidesBlock
{
   SPA_Guides guides;
};

// !SPA_GUIDES
#endif
